### ISSUE TITLE
Chamfer distance？

### ISSUE THREAD

**Issue by JKK-ja** [ddsediri/CLJNEPCF#1]
May I inquire with the author about the discrepancy in the chamfer distance measurement in the evaluation index? The final result ×10^-5 yields a value that is 10 times smaller than that reported in the paper. Seeking guidance on this matter. Thank you.

mycode：

def chamfer_distance(pcd1, pcd2):
    dists1_to_2 = pcd1.compute_point_cloud_distance(pcd2)
    dists2_to_1 = pcd2.compute_point_cloud_distance(pcd1)

    dists1_to_2_np = np.array(list(dists1_to_2)) ** 2
    dists2_to_1_np = np.array(list(dists2_to_1)) ** 2

    cd_forward = np.sum(dists1_to_2_np)
    cd_backward = np.sum(dists2_to_1_np)

    cd_total = (cd_forward + cd_backward) / 100000

    return cd_total

**Comment by ddsediri** [comment]
@JKK-ja how many points are in your point cloud? Is it 100,000 for both pcd1 and pcd2? That's to say, you must divide cd_forward and cd_backward by the number of points in each reference point cloud and then sum the two together to get the Chamfer distance.

Also, does the compute_point_cloud_distance function return the distance or the distance-squared from the reference point to the nearest neighbour in the target point cloud? 

Finally, it's important to check if the point clouds are correctly centered and normalized within the bounding diagonal. This could be the cause of the issue. In a preprocessing step, you must center both the GT and filtered point clouds and then normalize both GT and filtered point clouds by the GT bounding diagonal length.

**Comment by JKK-ja** [comment]
@ddsediri Thank you very much, I have successfully replicated the chamfer distance values in the article. Your article is excellent, and I have benefited a lot from it. Thank you for your guidance!

**Comment by ddsediri** [comment]
@JKK-ja great news! Glad our article has been of benefit to you. Good luck with your work!
